#pragma once

//Scene
#define ENEMYSPAWNRATE 5
#define WINDOWSIZE 600
#define AMOUNTOFTILESTYPES 3

//SceneInfected
#define INFECTEDENEMYSPAWNRATE 5
#define WINDOWSIZE 600
#define INFECTEDAMOUNTOFTILESTYPES 2

//Tower
#define FIRERATE 5
#define SHOT_DELAY 5.0f / FIRERATE
#define TOWERRADIUS 2.5f
#define TOWER_BUILD_TIME 2.5f

//Player
#define PLAYERFIRERATE 2
#define PLAYER_SHOT_DELAY 0.3f / PLAYERFIRERATE
#define PLAYER_RADIUS 0.5f
#define PLAYER_HIT_DELAY 1.0f

//Score
#define SCORETIMER 0.3f
#define STARTINGSCORE 10
#define TEXTUREWIDTH 1
#define TEXTUREHEIGHT 1

//Enemy
#define PATHFINDINGPATH 400
#define MAXHEALTH 100
#define LOWHEALTH 40.0f
#define LOWSPEED 1.0f
#define HIGHSPEED 2.0f
#define ENEMYRADIUS 0.8f;


//Bullet
#define BULLETRADIUS 0.2f;
#define BULLET_LIFETIME 2.5f